pipelines:
  custom: # Pipelines that can only be triggered manually
    build:
    - step:
        name: Build
        image: node:10.15.0
        caches:
          - node
        script: # build of each environment the selection is in httpd.conf
          - npm install
          - mkdir BuildEnvs
          - mkdir BuildEnvs/prod
          - mkdir BuildEnvs/test
          - REACT_APP_ENV_TYPE=prod
            REACT_APP_HEADER=
            npm run build
          - cp -r build/** BuildEnvs/prod/
          - REACT_APP_ENV_TYPE=test
            REACT_APP_HEADER=" - Test"
            npm run build
          - cp -r build/** BuildEnvs/test/
          - ls -r BuildEnvs
        artifacts: # defining the artifacts to be passed to each future step.
          - BuildEnvs/**
          - Dockerfile
          - httpd.conf
    - step:
        name: Create Container and push to google
        image: google/cloud-sdk
        script:
          - docker build -t mybenefitz-business-web .
          - gcloud auth activate-service-account --key-file registry-upload-prod.json
          - gcloud auth configure-docker --quiet
          - echo tag number is- $BITBUCKET_BUILD_NUMBER
          - docker tag mybenefitz-business-web gcr.io/warm-tangent-238911/mybenefitz-business-web:$BITBUCKET_BUILD_NUMBER
          - docker tag mybenefitz-business-web gcr.io/warm-tangent-238911/mybenefitz-business-web:latest
          - docker push gcr.io/warm-tangent-238911/mybenefitz-business-web
    - step:
        name: Deploy Test Server
        image: google/cloud-sdk
        deployment: test   # can be test, staging or production.
        trigger: manual  # Manual deployment.
        script:
          - gcloud auth activate-service-account --key-file keys/deploy-key-test.json
          - gcloud container clusters get-credentials my-benefitz-test --zone europe-west2-b --project total-pillar-234914
          - kubectl set image deploy/mybenefitz-business mybenefitz-business-web=gcr.io/warm-tangent-238911/mybenefitz-business-web:$BITBUCKET_BUILD_NUMBER
    - step:
        name: Deploy Staging Server
        image: google/cloud-sdk
        deployment: staging   # can be test, staging or production.
        trigger: manual  # Manual deployment.
        script:
          - echo Staging
#          - gcloud auth activate-service-account --key-file keys/deploy-key-staging.json
#          - kubectl set image deploy/mybenefitz-api mybenefitz-api=gcr.io/warm-tangent-238911/mybenefitz-api:$BITBUCKET_BUILD_NUMBER
    - step:
        name: Deploy Production Server
        image: google/cloud-sdk
        deployment: production # can be test, staging or production.
        trigger: manual # Manual deployment.
        script:
          - gcloud auth activate-service-account --key-file keys/deploy-key-prod.json
          - gcloud container clusters get-credentials my-benefitz-prod --zone us-central1-a --project warm-tangent-238911
          - kubectl set image deploy/mybenefitz-business mybenefitz-business-web=gcr.io/warm-tangent-238911/mybenefitz-business-web:$BITBUCKET_BUILD_NUMBER
options:
   docker: true
