pipelines:
  custom: # Pipelines that can only be triggered manually
    build:
    - step:
        name: Build
        image: node:10.15.0
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts: # defining the artifacts to be passed to each future step.
          - build/**
          - Dockerfile
          - httpd.conf
    - step:
        name: Create Container and push to google
        image: google/cloud-sdk
        script:
          - docker build -t mybenefitz-business-web .
          - gcloud auth activate-service-account --key-file registry-upload-prod.json
          - gcloud auth configure-docker --quiet
          - echo tag number is- $BITBUCKET_BUILD_NUMBER
          - docker tag mybenefitz-business-web gcr.io/warm-tangent-238911/mybenefitz-business-web:$BITBUCKET_BUILD_NUMBER
          - docker push gcr.io/warm-tangent-238911/mybenefitz-business-web:$BITBUCKET_BUILD_NUMBER
    - step:
        name: Deploy Server
        deployment: test   # can be test, staging or production.
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - echo "server deploy"
options:
   docker: true
